#!/usr/bin/env bash
# generate_report.sh — Generate Markdown summary report from analysis outputs
# Author: Claude Opus (AI-assisted)
# Status: AI-Enhanced — introduced by Claude Opus to supercharge mynlpbash
# Added advanced analytics, visualizations, and complex processing capabilities.
source "$(dirname "$0")/../lib/common.sh"

show_help() {
    print_help "generate_report" "Generate a Markdown summary report for a dataset" \
        "generate_report.sh -i data.csv -c label -t text [-o report.md]" \
        "-i, --input"      "Input CSV/TSV file" \
        "-c, --column"     "Label column" \
        "-t, --text-col"   "Text column" \
        "-d, --delimiter"  "Delimiter (auto-detected)" \
        "-o, --output"     "Output report file (default: report.md)" \
        "-h, --help"       "Show this help"
}

INPUT="" ; COLUMN="" ; TEXT_COL="" ; OUTPUT="report.md" ; DELIM=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -i|--input)     INPUT="$2"; shift 2 ;;
        -c|--column)    COLUMN="$2"; shift 2 ;;
        -t|--text-col)  TEXT_COL="$2"; shift 2 ;;
        -d|--delimiter) DELIM="$2"; shift 2 ;;
        -o|--output)    OUTPUT="$2"; shift 2 ;;
        -h|--help)      show_help; exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
done

[[ -z "$INPUT" ]] && die "Input file required (-i)"
require_file "$INPUT"
[[ -z "$DELIM" ]] && DELIM=$(detect_delimiter "$INPUT")

SCRIPT_DIR="$(dirname "$0")/.."
BASENAME=$(basename "$INPUT")

{
    echo "# Dataset Report: $BASENAME"
    echo ""
    echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "---"
    echo ""
    
    echo "## File Overview"
    echo ""
    echo '```'
    bash "$SCRIPT_DIR/file_processing/csv_stats.sh" -i "$INPUT" -d "$DELIM" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g'
    echo '```'
    echo ""
    
    if [[ -n "$COLUMN" ]]; then
        echo "## Class Distribution"
        echo ""
        echo '```'
        bash "$SCRIPT_DIR/classification/class_distribution.sh" -i "$INPUT" -c "$COLUMN" -d "$DELIM" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g'
        echo '```'
        echo ""
    fi
    
    if [[ -n "$COLUMN" && -n "$TEXT_COL" ]]; then
        echo "## Per-Label Statistics"
        echo ""
        echo '```'
        bash "$SCRIPT_DIR/classification/label_stats.sh" -i "$INPUT" -c "$COLUMN" -t "$TEXT_COL" -d "$DELIM" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g'
        echo '```'
        echo ""
    fi
    
    echo "## Data Quality"
    echo ""
    echo '```'
    bash "$SCRIPT_DIR/data_quality/missing_values.sh" -i "$INPUT" -d "$DELIM" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g'
    echo '```'
    echo ""
    
    echo "## Validation"
    echo ""
    echo '```'
    bash "$SCRIPT_DIR/file_processing/csv_validate.sh" -i "$INPUT" -d "$DELIM" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g'
    echo '```'
    echo ""
    
    echo "---"
    echo "*Report generated by mynlpbash*"
} > "$OUTPUT"

success "Report generated → $OUTPUT"
